### PR TITLE
Update the application name on consent screen when login to dashboard

### PR DESCRIPTION
**Pull request by SwatiNEC**
Update the application name on consent screen when login to dashboard [#3744](https://github.com/wso2/product-is/issues/3744)

### CODE REVIEW

**Comment by darshanasbg** [comment]
@thanujalk : Ain't we planning to add seperate display name for Service Provider to use places like this?

**Comment by thanujalk** [comment]
> @thanujalk : Ain't we planning to add seperate display name for Service Provider to use places like this?

@darshanasbg : We are allowing spaces in the service provider name. So the same value can be used as the display name.

**Comment by darshanasbg** [comment]
The generic issue tracked with: https://github.com/wso2/product-is/pull/4912

**Comment by madurangasiriwardena** [comment]
@SwatiNEC, Thank you for your contribution. This file is no longer in this place. PR https://github.com/wso2/product-is/pull/6037 has restructured this file and the module. So this PR has conflicts.

In the same time dashboard application is deprecated and will no longer be shipped with the product. 5.10.0 release will contain a brand new user portal application that will contain similar name as you have fixed.

**Pull request closed without merging**
