### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by PasinduYeshan**
$subject

### CODE REVIEW

**Review by sadilchamishka — APPROVED** [review]

**Review by lashinijay — APPROVED** [review]

**Review by ashensw — APPROVED** [review]

**Comment by darshanasbg** [comment]
Have we looked at the reason for why the build has failed 3 times for this PR?

**Comment by PasinduYeshan** [comment]
> Have we looked at the reason for why the build has failed 3 times for this PR?

It appears that the issue is caused by the introduction of new SCIM attributes under custom claims. I'm currently debugging the test locally to investigate further. In the meantime, I'll revert the changes.

**Comment by darshanasbg** [comment]
> > Have we looked at the reason for why the build has failed 3 times for this PR?
> 
> Seems like issue is caused by the introduction of new SCIM attributes under custom dialect. I'm currently debugging the test locally to investigate further. In the meantime, I'll revert the changes.

Seems we have noticed the same behavior in the PR test build in https://github.com/wso2/carbon-identity-framework/pull/5661.. So we have 4 signals (3 here and 1 in the framework repo) indicating an error, which we should have look at much earlier.. Lets do that next time.

**Comment by PasinduYeshan** [comment]
Integration test fix: 
- https://github.com/wso2/product-is/pull/21294

**Pull request closed without merging**
