### PR TITLE
Set subject attribute in EmailOTPTestCase

### PR DESCRIPTION
**Pull request by hwupathum**
Enable subject identifier in first step of 2FA from EmailOTPTestCase

### CODE REVIEW

**Comment by nilasini** [comment]
can you please attach the actual fix we introduced for this change?

**Comment by hwupathum** [comment]
This integration test change is related to https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/164

**Comment by nilasini** [comment]
Can you please give some more details on why we need to make the change in integration test?

**Comment by hwupathum** [comment]
In the PR https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/164 I added a null check for authenticatedUser vaiable and while debugging found out that the authenticatedUser becomes null in the  EmailOTPTestCase, which is not the correct behaviour

**Comment by nilasini** [comment]
Did we include this information(Attribute step should be enabled)  in our email OTP as first-factor documentation?

**Review by nilasini — APPROVED** [review]

**Comment by hwupathum** [comment]
The emailOTP authenticator can be used as the sceond factor without enabling attribute step, hence the no need to change integration test

**Pull request closed without merging**
