### PR TITLE
Include tomcat/carbon/WEB-INF/web.xml.j2 template in the product

### PR DESCRIPTION
**Pull request by chamathns**
$subject.
Include the `web.xml.j2` template in the `repository/resources/conf/templates/repository/conf/tomcat/carbon/WEB-INF` directory.
Related to https://github.com/wso2/product-is/issues/10380

### CODE REVIEW

**Comment by IsuraD** [comment]
> @pulasthi7 @IsuraD @senthalan The default values for the configurable properties have been added to the `modules/distribution/src/repository/resources/conf/default.json` in this PR. What should be the ideal place these default values should be put in?

I think it is fine to add default.json

**Review by IsuraD — APPROVED** [review]

**Comment by pulasthi7** [comment]
Since this is coming from kernel, the file should be templated at the kernal. Is there any particular reason to do it in the product?

We might miss the changes introduced at the kernel level if we go this path

**Comment by chamathns** [comment]
> Since this is coming from kernel, the file should be templated at the kernal. Is there any particular reason to do it in the product?
> 
> We might miss the changes introduced at the kernel level if we go this path

The reason for not templating it at the kernel level was to make sure the tomcat/carbon/WEB-INF/web.xml file in 

> Since this is coming from kernel, the file should be templated at the kernal. Is there any particular reason to do it in the product?
> 
> We might miss the changes introduced at the kernel level if we go this path

The reason why I went with product-level templating was to have the flexibility of adding product-specific configs and default values for the templated file. But, yes, I agree, by going down this path, we would miss changes introduced to this file at the kernel level.

**Comment by chamathns** [comment]
> Since this is coming from kernel, the file should be templated at the kernal. Is there any particular reason to do it in the product?
> 
> We might miss the changes introduced at the kernel level if we go this path

The reason why I went with product-level templating was to have the flexibility of adding product-specific configs and default values for the templated file. But, yes, I agree, by going down this path, we would miss changes introduced to this file at the kernel level.

**Comment by chamathns** [comment]
Closing this PR since the changes with https://github.com/wso2/carbon-kernel/pull/3115 would do the templating at the kernel level as suggested by @pulasthi7

**Pull request closed without merging**
